version: '3'

services:

  web:
    build: .
    ports:
      - "5432:5432"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/accountancy_data

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=accountancy_data
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: